select p.SPID linux_pid,
       vs.service_name,
       vs.module,
       vs.action,
       vs.osuser,
       vs.username,
       vs.logon_time,
       vs.sid,
       vs.serial#,
       vs.audsid,
       vs.user#,
       vs.process,
       vs.machine,
       vs.port,
       vs.terminal,
       vs.program,
       vs.type,
       vs.status,
       vs.server,
       vs.schemaname,
       vs.sql_id,
       vs.sql_child_number,
       vs.sql_exec_start,
       vs.sql_exec_id,
       vs.prev_sql_addr,
       vs.prev_hash_value,
       vs.prev_sql_id,
       vs.prev_child_number,
       vs.prev_exec_start,
       vs.prev_exec_id,
       vs.blocking_session_status,
       vs.blocking_instance,
       vs.blocking_session,
       vs.final_blocking_session_status,
       vs.final_blocking_instance,
       vs.final_blocking_session,
       vs.event#,
       vs.event,
       vs.state,
       vs.SECONDS_IN_WAIT,
       vs.wait_time,
       vs.wait_time_micro,
       vs.time_remaining_micro,
       vs.time_since_last_wait_micro,
       vs.sql_address,
       vs.sql_hash_value,
       round(p.PGA_USED_MEM     /1024/1024, 3)  PGA_USED_MEM    ,
       round(p.PGA_ALLOC_MEM    /1024/1024, 3)  PGA_ALLOC_MEM   ,
       round(p.PGA_FREEABLE_MEM /1024/1024, 3)  PGA_FREEABLE_MEM,
       round(p.PGA_MAX_MEM      /1024/1024, 3)  PGA_MAX_MEM     ,
       p.TRACEFILE from v$session vs,
       v$process p
where vs.osuser = 'oracle'--sys_context('userenv', 'os_user')
and   vs.module = 'emagent_SQL_oracle_database'
and p.ADDR(+) = vs.PADDR
order by vs.logon_time, vs.sid
