/*
DWHDATA,FONDDATA,FONDINDX,USERDATA,WEBDATA,ARHDATA,MDMDATA,OPSDATA,INFDATA,GFNDINDX,CTXDATA,MDMDAT2,FIASDATA,GFNDDAT2,GFPNDATA,GFPNINDX,SMPPDATA
*/
--/*
begin
  dbms_tts.transport_set_check(
    'DWHDATA,FONDDATA,FONDINDX,USERDATA,WEBDATA,ARHDATA,MDMDATA,OPSDATA,INFDATA,GFNDINDX,CTXDATA,MDMDAT2,FIASDATA,GFNDDAT2,GFPNDATA,GFPNINDX,SMPPDATA',
    true
  );
end;
/
select *
from   sys.transport_set_violations
/
--fnd.IZM_KEY_VAL
