--DROP TABLE files_pdb_ext_t
--/
CREATE TABLE files_pdb_ext_t(
message varchar2(2000)
) ORGANIZATION EXTERNAL (
  TYPE ORACLE_LOADER
  DEFAULT DIRECTORY PDB_CLONES_DIR
  ACCESS PARAMETERS (
    RECORDS DELIMITED BY NEWLINE
    PREPROCESSOR PDB_CLONES_DIR: 'files_pdb.sh'
  )
  LOCATION('clone_pdb.log'))
REJECT LIMIT UNLIMITED
/
