/*
https://www.techpaste.com/2012/07/generate-awr-report-oracle-database/
Generating Various Types of AWR Reports
AWR reports can be generated by running various SQL scripts to satisfy various requirements. Each report is available in HTML or TXT format:

— awrrpt.sql
Displays various statistics for a range of snapshots Ids.

— awrrpti.sql
Displays statistics for a range of snapshot Ids on a specified database and instance.

— awrsqrpt.sql
Displays statistics of a particular SQL statement for a range of snapshot Ids. Run this report to inspect or debug the performance of a particular SQL statement.

— awrsqrpi.sql
Displays statistics of a particular SQL statement for a range of snapshot Ids on a specified SQL.

— awrddrpt.sql
Compares detailed performance attributes and configuration settings between two selected time periods.

— awrddrpi.sql
Compares detailed performance attributes and configuration settings between two selected time periods on a specific database and instance.
*/
C:\Users\Admin>sqlplus /nolog

SQL*Plus: Release 11.2.0.1.0 Production on Mon Jul 9 16:04:02 2012

Copyright (c) 1982, 2010, Oracle. All rights reserved.

SQL> conn /as sysdba
Connected.
SQL> exec dbms_workload_repository.create_snapshot

PL/SQL procedure successfully completed.

( Reproduce the issue happening so that it will capture the details and once captured end the snapshot using below command )

SQL> exec dbms_workload_repository.create_snapshot

PL/SQL procedure successfully completed.

SQL> @?/rdbms/admin/awrrpt

Current Instance
~~~~~~~~~~~~~~~~

DB Id DB Name Inst Num Instance
----------- ------------ -------- ------------
1780233149 TECHPASTE 1 techpaste
Specify the Report Type
~~~~~~~~~~~~~~~~~~~~~~~
Would you like an HTML report, or a plain text report?
Enter 'html' for an HTML report, or 'text' for plain text
Defaults to 'html'
Enter value for report_type: html

Type Specified: html
Instances in this Workload Repository schema
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

DB Id Inst Num DB Name Instance Host
------------ -------- ------------ ------------ ------------
* 1780233149 1 TECHPASTE techpaste TechServer1

Using 1780233149 for database Id
Using 1 for instance number
Specify the number of days of snapshots to choose from
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Entering the number of days (n) will result in the most recent
(n) days of snapshots being listed. Pressing <return> without
specifying a number lists all completed snapshots.
Enter value for num_days:

Listing all Completed Snapshots

Snap
Instance DB Name Snap Id Snap Started Level
------------ ------------ --------- ------------------ -----
techpaste TECHPASTE 1162 02 Jul 2012 10:25 1
1163 02 Jul 2012 11:30 1
1164 02 Jul 2012 12:30 1
1165 02 Jul 2012 13:30 1
1166 02 Jul 2012 14:30 1
1167 02 Jul 2012 15:30 1
1168 02 Jul 2012 16:30 1
1169 02 Jul 2012 17:30 1
1170 03 Jul 2012 09:49 1
1171 03 Jul 2012 10:30 1
1172 03 Jul 2012 11:30 1
1173 03 Jul 2012 12:30 1
1174 03 Jul 2012 13:30 1
1175 03 Jul 2012 14:30 1
1176 03 Jul 2012 15:30 1
1177 03 Jul 2012 16:30 1
1178 03 Jul 2012 17:30 1
1179 03 Jul 2012 18:30 1
1180 04 Jul 2012 10:25 1
1181 04 Jul 2012 11:30 1
1182 04 Jul 2012 12:30 1
1183 04 Jul 2012 13:30 1
1184 04 Jul 2012 14:30 1
1185 04 Jul 2012 15:30 1
1186 04 Jul 2012 16:30 1
1187 04 Jul 2012 17:30 1
1188 05 Jul 2012 09:10 1
1189 05 Jul 2012 10:30 1
1190 05 Jul 2012 11:30 1
1191 05 Jul 2012 12:30 1
1192 05 Jul 2012 13:30 1
1193 05 Jul 2012 14:30 1
1194 05 Jul 2012 15:30 1
1195 05 Jul 2012 16:30 1
1196 05 Jul 2012 17:30 1
1197 06 Jul 2012 09:23 1
1198 06 Jul 2012 10:30 1
1199 06 Jul 2012 11:30 1
1200 06 Jul 2012 12:30 1
1201 06 Jul 2012 13:30 1
1202 06 Jul 2012 14:30 1
1203 09 Jul 2012 10:53 1
1204 09 Jul 2012 11:03 1
1205 09 Jul 2012 11:03 1
1206 09 Jul 2012 11:05 1
1207 09 Jul 2012 11:05 1
1208 09 Jul 2012 12:30 1
1209 09 Jul 2012 13:30 1
1210 09 Jul 2012 14:30 1
1211 09 Jul 2012 15:30 1
1212 09 Jul 2012 16:04 1
1213 09 Jul 2012 16:04 1

 

Specify the Begin and End Snapshot Ids
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Enter value for begin_snap: 1212
Begin Snapshot Id specified: 1212

Enter value for end_snap: 1213

(1212 and 1213 is the point where we reproduced the issue and took snapshot to diagnose the issue)

Specify the Report Name
~~~~~~~~~~~~~~~~~~~~~~~
The default report file name is awrrpt_1_1212_1213.html. To use this name,
press <return> to continue, otherwise enter an alternative.

Enter value for report_name: awr_report_techpaste.com.html

(--------------)
(--------------)
(--------------)

End of Report
</body></html>
Report written to awr_report_techpaste.com.html
SQL>exit
The awr_report_techpaste.com.html report gets generated at the same directory where you have executed the sql commands.
